name: Download Habbo Files
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      # articles
      - name: Download News Article Images
        run: node src/index.js -c articles -d it

      # badges
      - name: Download Badges
        run: node src/index.js -c badges -d it

      # hotelview
      - name: Download Hotelview Images
        run: node src/index.js -c hotelview

      # icons
      - name: Download Catalogue Icons
        run: node src/index.js -c icons

      # promo
      - name: Download Web Promo Images
        run: node src/index.js -c promo

      # commit
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: resource